{
 "title": "k8s 节点网络详细运行情况（network）",
 "tags": [
  "kubernetes",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "load（cpu）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "context switches（cpu）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{instance=~\"$node\"}[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "flannel receive packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（recv）"
    },
    {
     "expr": "rate(node_network_receive_drop{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（drop）"
    },
    {
     "expr": "rate(node_network_receive_errs{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（errs）"
    }
   ]
  },
  {
   "title": "flannel transmit packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（transmit）"
    },
    {
     "expr": "rate(node_network_transmit_drop{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（drop）"
    },
    {
     "expr": "rate(node_network_transmit_errs{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（errs）"
    }
   ]
  },
  {
   "title": "flannel receive bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（recv）"
    }
   ]
  },
  {
   "title": "flannel transmit bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{device=\"flannel.1\",instance=\"$node\"}[15m])",
     "legendFormat": "{{device}}（transmit）"
    }
   ]
  },
  {
   "title": "tcp state",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "inuse"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=~'$node'}",
     "legendFormat": "mem"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~'$node'}",
     "legendFormat": "orphan"
    }
   ]
  },
  {
   "title": "conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
     "legendFormat": "conntrack"
    }
   ]
  }
 ]
}