{
 "title": "k8s nginx ingress",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(nginx_ingress_controller_requests,namespace)"
   },
   {
    "name": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~'$Namespace$'}, ingress)"
   },
   {
    "name": "host",
    "query": "label_values(nginx_ingress_controller_response_size_count{namespace=~'$Namespace$'}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "ingress requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_namespace=\"$Namespace\",ingress=\"$Ingress\"}[10m])) by (ingress)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ingress}}(request)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ingress status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_namespace=\"$Namespace\",ingress=\"$Ingress\"}[10m])) by (status)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " {{status}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "平均时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_sum{controller_namespace=\"$Namespace\",host=\"$host\"}[10m]))by (host)/count(rate(nginx_ingress_controller_request_size_count{controller_namespace=\"$Namespace\",host=\"$host\"}[10m]))by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "a01-流量占总流量比例",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_namespace=\"$Namespace\",ingress=\"$Ingress\"}[10m]))/ sum(rate(nginx_ingress_controller_requests[10m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "nginx total upstream requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}