{
 "title": "tw06m1 k8s 集群边界节点运行情况（nginx ingress upstream）",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "upstream",
    "query": "label_values(nginx_upstream_requests_total,upstream)"
   },
   {
    "name": "status_code",
    "query": "label_values(nginx_upstream_responses_total, status_code)"
   }
  ]
 },
 "panels": [
  {
   "title": "tw06-upstream requests vs responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_requests_total{upstream=\"$upstream\"}[10m])) by (upstream)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{upstream}}（request）",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "- sum(rate(nginx_upstream_responses_total{upstream=\"$upstream\"}[10m])) by (upstream)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{upstream}}（response）",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "tw06-status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_responses_total{upstream=\"$upstream\",status_code=~\"$status_code\"}[10m])) by (status_code)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " {{status_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "tw06-平均时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_upstream_response_msecs_avg{upstream=\"$upstream\"})  by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "tw06-流量占总流量比例",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_requests_total{upstream=\"$upstream\"}[10m]))/ sum(rate(nginx_upstream_requests_total[10m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "nginx total upstream requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}